/**
 * 타입캐스트 캐릭터 한글 이름 (한국어 캐릭터 442종).
 *
 * 공개 API(`/v1/voices`)는 로마자 이름만 준다 — 스튜디오 화면의 「용식이」가 API에서는
 * `Yongsik`이다. 로마자를 한글로 되돌리는 규칙은 없어서(Aaron도 「아아론」으로 풀린다)
 * 2026-08-18에 스튜디오 캐릭터 목록의 `name.en`·`name.ko`를 한 번 받아 적어 둔 표다.
 * 앱은 이 표만 읽고 스튜디오를 다시 부르지 않는다 — 비공식 경로에 실행을 묶지 않는다.
 *
 * 표에 없는 이름(외국어 캐릭터 등)은 로마자 이름을 그대로 쓴다. 캐릭터가 늘면 한 줄 더 적는다.
 */
export const VOICE_KO: Record<string, string> = {
  "Ae-ran": "애란",
  Ael: "아엘",
  "Anchor Hwa": "김경화 앵커",
  Arang: "아랑",
  Ari: "아리",
  Arin: "아린",
  Avong: "아봉",
  Azzi: "아찌",
  Babilon: "바빌론",
  Babyhippo: "함마",
  Bboddo: "뽀또",
  Beomtting: "범띵",
  Beri: "베리",
  Biriri: "삐리리",
  Biteman: "이악남",
  Bomi: "이보미",
  Bonggyu: "봉규",
  "Bongman Kim": "김봉만",
  Bono: "보노",
  Booqoo: "부끄",
  Bora: "보라",
  Bumsoo: "범수",
  Buttaguy: "빠다가이",
  Byunghun: "병훈",
  Chaeah: "채아",
  Chaelin: "채린이",
  "Chan-gu": "찬구",
  Changbae: "창배",
  Changhee: "창희",
  Changmin: "창민",
  Changsu: "박창수",
  Chanhyuk: "찬혁",
  "Cheap Noble": "천박 귀족",
  Cheolhoon: "철훈",
  Cheolyong: "리철용",
  Cherry: "체리",
  Chiho: "치호",
  Choyeon: "강초연 교관",
  Chungah: "청아",
  "Chunsik Kang": "강춘식 기자",
  "Classic Narrator": "미스타 변사",
  Cox: "콕스",
  Crankyman: "까칠한",
  Dabin: "다빈",
  Daegil: "대길",
  Daejin: "대진",
  Daeun: "다은",
  Dahee: "다희",
  Dahyeon: "다현",
  Dana: "다나",
  Dasom: "다솜",
  Deokhwan: "덕환",
  Dohan: "도한",
  Dohee: "도희",
  Dohyun: "도현",
  Donggulajeossi: "동굴아저씨",
  Down: "따운쓰",
  Doyoon: "도윤",
  DU5T: "더스트",
  Duckchun: "덕춘",
  Dukgu: "덕구",
  Duman: "두만",
  Dupil: "곽두필",
  DVZY: "데이지",
  "E Ru": "이루",
  "E-seller Sherri": "쇼린이",
  Edo: "이도",
  Eogwool: "억울이",
  Eunbin: "은빈",
  Eunchae: "은채",
  Eunha: "은하",
  Eunkyung: "은경",
  Eunsol: "은솔",
  "Film Teller": "영소남",
  "Fussy Youth": "호들갑 청년",
  Gaeul: "가을",
  Gahee: "가희",
  Geonhee: "건희",
  GeumHee: "금희",
  Geunhyeok: "근혁",
  Geunseok: "근석",
  Geunwoo: "근우",
  Geunyeong: "근영",
  Ggami: "까미",
  Ggolddak: "숨꼴딱",
  Ggomi: "꼬미",
  Ggoolsister: "꿀꿀여사님",
  "Goat Kim": "김고트",
  Gongchul: "공철",
  Gowoon: "고운",
  "Gunn Kim": "김건",
  Gunseok: "건석",
  Gunwoo: "건우",
  Guri: "구리",
  "Ha Eun": "하은",
  Haejun: "해준",
  Haerang: "해랑",
  Hajun: "하준",
  Hakchul: "학철",
  Hamchu: "햄쮸",
  "Han Taesung Caster": "한태성 캐스터",
  Hana: "하나",
  Hangeri: "한그리",
  Hangyeol: "한결",
  Hanjun: "한준",
  Hanna: "한나",
  Hansol: "한솔",
  Hanyoung: "한영",
  Harin: "하린",
  "Hattie Mama": "퉁실마마",
  Hayoon: "하윤",
  Hayoung: "하영",
  Hayul: "하율",
  Heejoon: "희준",
  Hobin: "호빈이",
  "Homun Sim": "심호문",
  Hoon: "훈",
  Hosik: "호식",
  Hosun: "호선",
  Hoyoung: "호영",
  Hwimin: "휘민",
  Hwiso: "휘소",
  Hyeji: "혜지",
  Hyejin: "혜진",
  Hyejung: "혜정",
  Hyelee: "혜리",
  Hyemin: "혜민",
  Hyena: "혜나",
  Hyeongjin: "형진",
  Hyeonseok: "현석",
  Hyera: "혜라",
  Hyesu: "홈쇼핑 혜수",
  Hyewon: "혜원",
  Hyoeun: "효은",
  Hyun: "현",
  Hyunji: "현지",
  Hyunjin: "현진",
  Hyunju: "현주",
  Hyunjun: "현준",
  Hyunkyung: "현경",
  Hyunmin: "현민",
  Hyunseung: "현승",
  HyunWoo: "현우",
  Ian: "이안",
  Igyeom: "이겸",
  Ijun: "이준",
  Ilho: "일호",
  Ina: "이나",
  Inhwa: "인화",
  Inhye: "인혜",
  Inseong: "인성",
  "Instructor Han": "한유격 교관",
  Insun: "인선",
  Jabbaba: "자바바",
  Jackie: "명진",
  Jaeho: "재호",
  Jaehun: "재훈",
  Jaejun: "재준",
  Jaekyung: "재경",
  Jaesun: "재선",
  JaeYi: "재이",
  Jaeyoung: "재영",
  Jain: "자인",
  Jangho: "장호",
  Jangwoon: "장운",
  Jechan: "제찬",
  "Jeong Choi": "최정",
  Jeongah: "정아",
  JeongJin: "정진",
  Jeongseob: "정섭",
  Jerome: "제롬",
  Jewby: "쥬비",
  Jian: "지안",
  Jicheol: "지철",
  Jihee: "지희",
  Jihoon: "지훈",
  Jihyun: "지현",
  Jin: "진",
  Jinhan: "진한",
  "Jinhang Kim": "김진행",
  Jinhee: "진희",
  Jinhyuk: "진혁",
  Jinseo: "진서",
  Jinung: "진웅",
  Jinwoo: "진우",
  Jiseon: "지선",
  Jiwoo: "지우",
  Jiyoon: "지윤",
  Jiyoung: "지영",
  Jolly: "졸리",
  Jongdae: "종대",
  Jooeun: "주은",
  Joojin: "주진",
  Joonchic: "준식",
  Joonghyun: "중현",
  Joongsik: "중식",
  Joonkyu: "준규",
  Juha: "주하",
  Juho: "주호",
  Jungbong: "정봉",
  Junghee: "정희",
  Jungjae: "정재",
  Jungmin: "정민",
  Jungseok: "정석",
  Jungsook: "정숙",
  Jungsoon: "정순",
  Jungwon: "정원",
  Junhee: "준희",
  Junho: "준호",
  JunKi: "준기",
  Junney: "주니",
  Junsang: "준상",
  Junseong: "준성",
  "Justice Roh": "정의로",
  Juwan: "주완",
  Juwon: "주원",
  Juyoung: "주영",
  "K-Santa": "산타 할아버지",
  Kangil: "강일",
  "Kijang Kim": "김기장",
  "Kim Hoin": "김호인",
  Kiseob: "기섭",
  Knowell: "지식이",
  Kukhee: "국희",
  Kwonil: "권일",
  Kyumin: "규민",
  Kyungho: "경호",
  Kyungsoo: "경수",
  Kyungsook: "경숙",
  "Lady Cho": "단희빈",
  Lala: "라라",
  Lamie: "라미",
  Layla: "라일라",
  Leehyun: "이현",
  Lumina: "루미나",
  Luna: "루나",
  Masterboo: "마스터 부",
  "MBTI EF (F)": "MBTI EF 여",
  "MBTI EF (M)": "MBTI EF 남",
  "MBTI ET (F)": "MBTI ET 여",
  "MBTI ET (M)": "MBTI ET 남",
  "MBTI IF (F)": "MBTI IF 여",
  "MBTI IF (M)": "MBTI IF 남",
  "MBTI IT (F)": "MBTI IT 여",
  "MBTI IT (M)": "MBTI IT 남",
  "MC Kong": "MC콩",
  "MC MIJA": "MC미자",
  "MC TypeCast": "MC 타캐",
  Mija: "오미자",
  Mijin: "미진",
  Mikyung: "미경",
  Minchae: "민채",
  Minhee: "민희",
  Minji: "민지",
  Minjoon: "민준",
  Minju: "민주",
  Minjung: "민정",
  Minsang: "민상",
  Minsu: "민수",
  Minuk: "민욱",
  Mio: "미오",
  "Miran Choi": "최미란",
  Mirine: "미리내",
  Miseon: "미선",
  Miso: "미소",
  "Mister Gop": "미스터 갑",
  Monggun: "몽군",
  Mongsil: "몽실이",
  Moonjung: "문정",
  Mooyeol: "무열",
  Morgan: "모건",
  Moru: "머루",
  Munseok: "문석",
  Munsu: "문수",
  Muyoung: "무영",
  Myeonghee: "명희",
  Myungil: "명일",
  Myungjoo: "명주",
  Naeun: "나은",
  NAGYOYUK: "나교육",
  Najin: "나진",
  Namjoon: "남준",
  Nari: "개나리",
  "News anchor Jinsub": "송진섭 앵커",
  Noeul: "노을",
  Okji: "옥지",
  "Old radio": "레디오",
  Pacang: "파캉",
  Pangpang: "팡팡",
  Peach: "복숭아",
  Piljae: "필재",
  Pyeonghwa: "평화",
  Rapid: "일쩜오",
  Rayeon: "라연",
  "Reporter Bona": "다보나 기자",
  "Reporter Jinsub": "송진섭 기자",
  "Reporter Kang": "강수정 기자",
  "Reporter Lee": "이승주 기자",
  "Reporter Parkchan": "박찬 기자",
  "Risan Ji": "지리산",
  Robo: "로보",
  Romi: "로미",
  Roro: "로로",
  Rowoon: "로운",
  Ruri: "루리",
  Ryueun: "류은",
  Saeron: "새론",
  "Salty Chan-gu": "삐뚤어진 찬구",
  Sammy: "새미",
  Sandra: "우아한 디제이",
  Sangdo: "상도",
  Sanghoon: "상훈",
  Sanghyun: "상현",
  Sangwoo: "상우",
  "Santa Reporter": "VJ 싼타",
  "Scary girl": "한서린",
  SeHee: "세희",
  Seheon: "세헌",
  Sejin: "세진",
  Sena: "세나",
  Seoblin: "서블린",
  Seohee: "서희",
  Seohyeon: "서현",
  Seojin: "서진",
  Seojoon: "서준",
  "Seok Choi": "최석",
  SeokPil: "한석필",
  Seokpyo: "석표",
  Seolhwa: "설화",
  Seonha: "선하",
  Seoyeon: "서연",
  Seoyoon: "서윤",
  Seungah: "승아",
  Seungheon: "승헌",
  Seungho: "승호",
  Seunghwa: "승화",
  Seungjae: "승재",
  Seungmoon: "승문",
  Seungwon: "승원",
  Seungyeon: "승연",
  Sewoo: "세우",
  "Sheriff Kim": "김반장",
  Shinhe: "신혜",
  Shinwook: "신욱",
  Shoe: "왔슈",
  Shotgun: "샷건",
  Sio: "시오",
  Siwon: "시원",
  Siwoo: "시우",
  Siyeon: "시연",
  "Sleep Helper": "수면남친",
  Smoke: "스모크",
  Sohye: "소혜",
  Sojin: "소진",
  Soobin: "수빈",
  Sookhee: "숙희",
  Sooni: "순이",
  Soonnam: "순남",
  Sora: "소라",
  Soye: "소예",
  Soyi: "소이",
  Soyoung: "소영",
  Soyul: "소율",
  Spice: "스파이스",
  "Sportscaster Kang": "강수정 캐스터",
  "Sportscaster Tony": "이영광 캐스터",
  "Storyteller Jinsub": "송진섭 스토리텔러",
  Sua: "수아",
  Suho: "수호",
  Suji: "수지",
  Sujin: "수진",
  "Sullock Hong": "홍설록",
  Sumin: "수민",
  Sungbae: "성배",
  Sunggyu: "성규",
  Sungho: "성호",
  Sunghoon: "성훈",
  Sunghyun: "성현",
  Sungjun: "홈쇼핑 성준",
  Sungkwon: "성권",
  Sungtae: "성태",
  Sungwook: "성욱",
  Sunmin: "순민",
  Sunyoung: "선영",
  Suyoon: "수윤",
  "Sweet Guy Sany": "훈남산이",
  Taebaek: "장태백",
  Taeji: "태지",
  Taejoong: "태중",
  Taemin: "태민",
  Taesub: "태섭",
  Taewoo: "태우",
  Taeyui: "회장 청소년",
  Tara: "타라",
  Teal: "틸",
  Tian: "티안",
  Tiger: "타이가",
  Toby: "토비",
  Ttaenggu: "땡구",
  Turultultul: "투룰툴툴",
  Twistman: "장꼬불",
  UiChan: "의찬이",
  Valkyrie: "발키리",
  Wangkwon: "왕권",
  "Weather Reporter Sky": "하늘 캐스터",
  Wonho: "원호",
  Wonkyung: "원경",
  Wonwoo: "원우",
  Wooju: "우주",
  Woony: "우니",
  Woosung: "우성",
  Yeeun: "예은",
  Yejin: "예진",
  Yejoon: "예준",
  YeLin: "예린",
  Yena: "예나",
  Yeonah: "연아",
  Yeonggeol: "영걸",
  Yeonhwa: "연화",
  Yeonja: "연자",
  Yeonsuh: "연서",
  Yeonwoo: "연우",
  Yeseul: "예슬",
  Yongsik: "용식이",
  Yoonseo: "윤서",
  Yoonsung: "윤성",
  Younggil: "영길",
  Younghee: "영희",
  Younghwan: "영환",
  Youngji: "영지",
  Youngkyu: "영규",
  Youngmok: "영목",
  Yubin: "유빈",
  Yuha: "유하",
  Yujin: "유진",
  Yumi: "유미",
  Yumin: "유민",
  Yunbin: "윤빈",
  Yunjeong: "윤정",
  Yura: "유라",
  Yuri: "유리",
  Yuseong: "유성",
};

/** 화면에 보일 이름 — 한글이 있으면 한글 우선, 로마자는 괄호로 남긴다(검색·대조용) */
export function voiceLabel(name: string): string {
  const ko = VOICE_KO[name];
  return ko ? `${ko} (${name})` : name;
}
